version: "3"

services:
  back:
    build: ./back/
    container_name: website-back
    restart: always
    volumes:
      - ./back:/app
    ports:
      - "4000:4000"
      - "81:81"
    environment:
      PORT: 4000
      FRONT_URI: "http://localhost:3000"
      FORTYTWO_OAUTH_UID: "d9a640fbf91b4972fb036c891250529f1d7568bc8128fd3c76d5d7197e365cc8"
      FORTYTWO_OAUTH_SECRET: "dfb0144b6eaf6e50674e9709b24f2190d8f0340ee129e526f361d443672a3b56"
      JWT_SECRET: "QHrcpsyyf4D57voYDqRWwMxa/Zc="
      OAUTH_REDIRECT_URL: "http://localhost:3000/auth/42"
      MJ_APIKEY_PUBLIC: "9a5bf8d71c95a4c3ea3997f307e430f2"
      MJ_APIKEY_SECRET: "26015fd2c8948da4b89b79cf21459034"
    command: "yarn start:dev"
    depends_on:
      - db
  front:
    build: ./front/
    container_name: website-front
    restart: always
    volumes:
      - ./front:/app
    ports:
      - "3000:3000"
    environment:
      BASE_URL: "http://localhost:4000"
      SOCKET_IO_URI: "http://localhost:81"
      SSR_BACKEND_BASE_URL: "http://back:4000"
      OAUTH_REDIRECT_URL: "http://localhost:3000/auth/42"
      FORTYTWO_OAUTH_UID: "d9a640fbf91b4972fb036c891250529f1d7568bc8128fd3c76d5d7197e365cc8"
    command: "yarn dev"
    depends_on:
      - back
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/.tmp/db:/var/lib/postgresql/data
      - ./postgres/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /tmp
